image:
 name: hashicorp/terraform:0.13.4        

stages:
 - infra_test
 - infra_apply
 - infra_destroy

# tests the tf infrastructure   
infra_test:
 stage: infra_test
 tags:
  - bash        
 script:
  - terraform init .      
  - terraform validate .

# deploy the tested tf infrastructure    
infra_apply:
 stage: infra_apply
 tags:
  - bash        
 script:
  - terraform init -var="group_id=d3" .
  - terraform apply -var="group_id=d3" -auto-approve .  
 artifacts:
  name: "terraform.tfstate"
  paths: 
   - public
  expire_in: 2 weeks   
 dependencies:
  - infra_test       

# manually destroy the deployed tf infrastrucure   
infra_destroy:
 stage: infra_destroy
 tags:
  - bash        
 script:
  - terraform init .
  - terraform destroy -var="group_id=d3" -auto-approve .
 dependencies:
  - infra_apply       
 when: manual       
